import {asset} from './assets.js';
import React, {useState, useEffect, useRef} from 'react';
import {ArrowUpRight, ArrowDown, ArrowRight, Plus, Minus, RotateCcw, Move, Menu, X, Snowflake, Phone, Copy, Check, MapPin, Layers, Box, Pause, Play} from 'lucide-react';
import {SystemScene} from './Scenes.jsx';
import {ProductScene} from './DetailedProduct.jsx';
import {copy, products} from './content.js';

export function App(){
 const [lang,setLang]=useState(()=>{try{return localStorage.getItem('minyou-language')==='en'?'en':'zh'}catch{return 'zh'}});
 const t=copy[lang]; const [mode,setMode]=useState('blueprint'),[rotate,setRotate]=useState(true),[zoom,setZoom]=useState(1),[reset,setReset]=useState(0);
 const [application,setApplication]=useState(0),[running,setRunning]=useState(true),[step,setStep]=useState(0),[filter,setFilter]=useState(-1),[detail,setDetail]=useState(null),[interest,setInterest]=useState(null),[menu,setMenu]=useState(false),[copied,setCopied]=useState(false),[sceneReady,setSceneReady]=useState(false);
 const [active,setActive]=useState('top');const modal=useRef(null);const lastFocus=useRef(null);
 useEffect(()=>{document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.title=lang==='zh'?'民主制冷 | 玉环民主制冷实业有限公司':'Minzhu Refrigeration | Compressors & Cooling Systems';try{localStorage.setItem('minyou-language',lang)}catch{}},[lang]);
 useEffect(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){setRotate(false);setRunning(false)}},[]);
 useEffect(()=>{if(!running)return;let timer=setInterval(()=>setStep(s=>(s+1)%4),3200);return()=>clearInterval(timer)},[running]);
 useEffect(()=>{if(detail!==null){lastFocus.current=document.activeElement;modal.current.showModal()}else if(modal.current?.open){modal.current.close();lastFocus.current?.focus()}},[detail]);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting)setActive(e.target.id)},{rootMargin:'-20% 0px -45% 0px'});document.querySelectorAll('section[id]').forEach(s=>observer.observe(s));return()=>observer.disconnect()},[]);
 function inquire(i){setInterest(i);setDetail(null);setTimeout(()=>document.getElementById('contact').scrollIntoView({behavior:'smooth'}),0)}
 async function copyPhone(){try{await navigator.clipboard.writeText(lang==='zh'?'13905866435':'+86 13905866435');setCopied(true);setTimeout(()=>setCopied(false),2200)}catch{window.prompt(t.copy,'+86 13905866435')}}
 const nav=(id,i)=><a href={'#'+id} onClick={()=>setMenu(false)} className={active===id?'active':''}>{t.nav[i]}</a>;
 return <>
 <a className="skip-link" href="#products">{lang==='zh'?'跳至产品':'Skip to products'}</a>
 <header className="header"><a className="brand" href="#top" aria-label={lang==='zh'?'民主制冷首页':'Minzhu home'}><Snowflake size={29} strokeWidth={1.5}/><span className="brand-word">MINZHU<span>{lang==='zh'?'民主制冷':'REFRIGERATION'}</span></span></a><nav className="desktop-nav" aria-label="Main">{nav('products',0)}{nav('applications',1)}{nav('about',2)}</nav><div className="header-actions"><button className="language" onClick={()=>setLang(l=>l==='zh'?'en':'zh')} aria-label={lang==='zh'?'Switch to English':'切换中文'}><span className={lang==='zh'?'selected':''}>中</span><span className="slash">/</span><span className={lang==='en'?'selected':''}>EN</span></button><a className="contact-pill" href="#contact">{t.contact}<ArrowUpRight size={17}/></a><button className="menu-toggle icon-button" aria-label={t.menu} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
 {menu&&<nav className="mobile-nav">{nav('products',0)}{nav('applications',1)}{nav('about',2)}<a href="#contact" onClick={()=>setMenu(false)}>{t.contact}</a></nav>}
 <main>
 <section id="top" className="hero panel"><div className="hero-topline"><span>{t.eyebrow}</span><span>EST. 1992 — YUHUAN, CN</span></div><div className="hero-copy"><h1>{t.title[0]}<br/><span>{t.title[1]}</span></h1><p>{t.intro}</p><a className="text-link" href="#products">{t.explore}<span className="round-arrow"><ArrowUpRight size={21}/></span></a></div>
 <div className="product-stage"><ProductScene mode={mode} rotate={rotate} zoom={zoom} reset={reset} onReady={()=>setSceneReady(true)} lang={lang}/>{!sceneReady&&<div className="scene-loading">{lang==='zh'?'正在加载产品视图…':'Loading product view…'}</div>}<div className="model-tag"><span className="tiny-dot"/> {t.modelSub}</div><div className="stage-caption"><span>01 — {t.model}</span><small>{t.modelNote}</small></div></div>
 <div className="hero-bottom"><a href="#applications" className="scroll-link"><ArrowDown size={16}/>{t.scroll}</a><div className="model-controls"><div className="segmented" aria-label={lang==='zh'?'展示模式':'Display mode'}><button className={mode==='blueprint'?'on':''} onClick={()=>setMode('blueprint')} aria-pressed={mode==='blueprint'}><Layers size={14}/>{t.blueprint}</button><button className={mode==='solid'?'on':''} onClick={()=>setMode('solid')} aria-pressed={mode==='solid'}><Box size={14}/>{t.solid}</button></div><span className="control-divider"/><button className="icon-button" title={rotate?(lang==='zh'?'暂停展示':'Pause showcase'):(lang==='zh'?'播放展示':'Play showcase')} aria-label={rotate?(lang==='zh'?'暂停展示':'Pause showcase'):(lang==='zh'?'播放展示':'Play showcase')} onClick={()=>setRotate(!rotate)}>{rotate?<Pause size={16}/>:<Play size={16}/>}</button><button className="icon-button" title={t.reset} aria-label={t.reset} onClick={()=>{setReset(n=>n+1);setZoom(1)}}><RotateCcw size={16}/></button><button className="icon-button zoom-button" title={t.zoomOut} aria-label={t.zoomOut} disabled={zoom<=.8} onClick={()=>setZoom(Math.max(.8,zoom-.15))}><Minus size={16}/></button><button className="icon-button zoom-button" title={t.zoomIn} aria-label={t.zoomIn} disabled={zoom>=1.4} onClick={()=>setZoom(Math.min(1.4,zoom+.15))}><Plus size={16}/></button></div><span className="drag-hint"><Move size={13}/>{lang==='zh'?'自动循环 · 拖动查看':'Auto loop · Drag to explore'}</span></div></section>
 <div className="intro-strip"><div><span className="strip-index">A.</span><div><strong>{t.since}</strong><span>{t.sinceNote}</span></div></div><div><span className="strip-index">B.</span><div><strong>{t.range}</strong><span>{t.rangeNote}</span></div></div><a href="#about" aria-label={t.nav[2]}><ArrowDown size={23}/></a></div>
 <section id="applications" className="application-section"><div className="section-heading"><p className="eyebrow">{t.systemKicker}</p><div className="heading-row"><h2>{t.systemTitle[0]}<br/>{t.systemTitle[1]}</h2><p className="section-intro">{t.systemIntro}</p></div></div>
 <div className="system-layout"><div className="system-view panel"><div className="system-top"><span><i className={running?'live-dot':'live-dot paused'}/>{running?t.running:t.stopped}</span><button className="icon-button" title={running?t.pauseSystem:t.playSystem} aria-label={running?t.pauseSystem:t.playSystem} onClick={()=>setRunning(!running)}>{running?<Pause size={16}/>:<Play size={16}/>}</button></div><SystemScene running={running} step={step} application={application} lang={lang}/><div className="system-legend"><span><i className="legend-blue"/>{lang==='zh'?'低压侧 / 吸热':'LOW PRESSURE / ABSORPTION'}</span><span><i className="legend-orange"/>{lang==='zh'?'高压侧 / 放热':'HIGH PRESSURE / RELEASE'}</span></div><small className="system-note">{t.systemNote}</small></div><div className="system-explanation"><div className="application-tabs" role="tablist" aria-label={lang==='zh'?'应用场景':'Applications'}>{t.tabs.map((x,i)=><button key={i} role="tab" id={'tab-'+i} aria-controls="application-panel" aria-selected={application===i} className={application===i?'active':''} onClick={()=>setApplication(i)} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();let n=(application+(e.key==='ArrowRight'?1:2))%3;setApplication(n);document.getElementById('tab-'+n)?.focus()}}}>{x}</button>)}</div><p id="application-panel" role="tabpanel" aria-labelledby={'tab-'+application} className="application-description">{t.appDescriptions[application]}</p><div className="flow-steps">{t.flow.map((x,i)=><button key={i} className={'flow-step '+(step===i?'active':'')} onClick={()=>{setStep(i);setRunning(false)}} aria-pressed={step===i}><span className="flow-num">0{i+1}</span><div><strong>{x}</strong>{step===i&&<p>{t.flowDesc[i]}</p>}</div><ArrowUpRight size={17}/></button>)}</div><a className="text-link smaller" href="#contact">{t.contact}<ArrowUpRight size={19}/></a></div></div></section>
 <section id="products" className="products-section"><div className="section-heading"><p className="eyebrow">{t.productKicker}</p><div className="heading-row"><h2>{t.productTitle}</h2><p className="section-intro">{t.productIntro}</p></div></div><div className="product-toolbar"><div className="filter-list">{[t.all,...t.filters].map((x,i)=><button key={i} className={filter===i-1?'active':''} aria-pressed={filter===i-1} onClick={()=>setFilter(i-1)}>{x}</button>)}</div><span className="product-count">{products.filter(p=>filter===-1||filter===p.category).length.toString().padStart(2,'0')} {lang==='zh'?'款展示产品':'PRODUCTS'}</span></div><div className="product-grid">{products.map((p,i)=>filter!==-1&&filter!==p.category?null:<button className="product-card" key={i} onClick={()=>setDetail(i)}><div className="product-image"><span className="product-number">0{i+1}</span><img src={asset('assets/'+p.img)} alt={t.productNames[i]} loading="lazy"/><span className="product-open"><ArrowUpRight size={21}/></span></div><div className="product-info"><span>{t.productTypes[i]}</span><h3>{t.productNames[i]}</h3><p>{t.detail}<ArrowRight size={15}/></p></div></button>)}</div></section>
 <section id="about" className="about-section panel"><div className="about-copy"><p className="eyebrow">{t.aboutKicker}</p><h2>{t.aboutTitle[0]}<br/>{t.aboutTitle[1]}</h2><p>{t.aboutBody}</p><p>{t.aboutExtra}</p><p>{t.aboutCooperation}</p></div><div className="about-data"><div className="year">1992<span>{t.founded}</span></div><div className="about-stat"><span>{t.locationLabel}</span><strong>{t.location}</strong></div><div className="about-stat"><span>{t.categories}</span><strong>{t.categoriesValue}</strong></div></div><div className="company-photos"><p>{t.photoContext}</p><div><figure><img src={asset('assets/company-compressors.jpg')} alt={t.factoryCaption} loading="lazy"/><figcaption>{t.factoryCaption}</figcaption></figure><figure><img src={asset('assets/company-units.jpg')} alt={t.unitCaption} loading="lazy"/><figcaption>{t.unitCaption}</figcaption></figure></div></div></section>
 <section id="contact" className="contact-section"><div><p className="eyebrow">{t.contactKicker}</p><h2>{t.contactTitle[0]}<br/>{t.contactTitle[1]}</h2><p className="contact-intro">{t.contactIntro}</p>{interest!==null&&<div className="interest-badge">{t.interest}：{t.productNames[interest]}<button aria-label={t.clear} onClick={()=>setInterest(null)}><X size={14}/></button></div>}<p className="contact-tip">{t.contactTip}</p></div><div className="contact-details"><span className="contact-person">{t.person}</span><a className="big-phone" href="tel:+8613905866435">{lang==='en'&&<small>+86 </small>}139 0586 6435<ArrowUpRight/></a><div className="contact-buttons"><a className="contact-pill" href="tel:+8613905866435"><Phone size={16}/>{t.phone}</a><button className="copy-button" onClick={copyPhone}>{copied?<Check size={16}/>:<Copy size={16}/>}<span aria-live="polite">{copied?t.copied:t.copy}</span></button></div><div className="contact-meta"><p><Phone size={16}/><span>{t.landline}：<a href="tel:+8657687562433">+86 0576 87562433</a></span></p><p><MapPin size={17}/><span>{t.address}</span></p></div></div></section>
 </main><footer><div className="footer-top"><a className="brand" href="#top"><Snowflake size={27}/><span className="brand-word">MINZHU<span>{t.footer}</span></span></a><a href="#top" className="back-top">{t.back}<ArrowUpRight size={18}/></a></div><div className="footer-bottom"><span>{t.company}<br/><small>{t.englishCompany}</small></span><span>© {new Date().getFullYear()} MINZHU</span><a href="https://taizhou0146217.11467.com/" target="_blank" rel="noreferrer">{t.source}<ArrowUpRight size={12}/></a></div></footer>
 <dialog ref={modal} className="product-dialog" onCancel={()=>setDetail(null)} onClick={e=>{if(e.target===modal.current)setDetail(null)}}>{detail!==null&&<><button className="dialog-close icon-button" aria-label={t.close} onClick={()=>setDetail(null)}><X/></button><div className="dialog-image"><img src={asset('assets/'+products[detail].img)} alt={t.productNames[detail]}/><span>{t.sourcePhoto}</span></div><div className="dialog-copy"><p className="eyebrow">{t.productTypes[detail]}</p><h2>{t.productNames[detail]}</h2><p>{t.productDesc[detail]}</p><small>{t.photoNote}</small><button className="contact-pill" onClick={()=>inquire(detail)}>{t.askProduct}<ArrowUpRight size={18}/></button></div></>}</dialog>
 </>;
}
