import {BrandMark} from './BrandMark.jsx';
import React,{useState,useEffect} from 'react';
import {asset} from './assets.js';
import {popularProducts,nominalPowerText,productTitle,productDescription,productSeo,specificationGroups} from './products.js';
export const initialLanguage=()=>{try{return localStorage.getItem('minyou-language')==='zh'?'zh':'en'}catch{return 'en'}};
export const detailUrl=p=>asset(`products/${p.slug}/`);
const choose=(lang,en,zh)=>lang==='zh'?zh:en;
// Source-page coordinates at 1344 px width; CSS windows preserve every source pixel.
const photos={small:[24,450,438,345,274],medium:[24,832,292,410,270],large:[26,112,894,452,295],six:[26,102,502,453,298]};
const drawings={small:[25,155,327,1035,590],medium:[25,155,327,1035,590],large:[27,95,403,1150,352],six:[27,95,869,1150,345]};
export function SourceFigure({product,drawing=false,lang='en'}){const [page,x,y,w,h]=(drawing?drawings:photos)[product.photoFamily];return <div className={'source-figure '+(drawing?'drawing':'')} style={{aspectRatio:`${w}/${h}`}}><img src={asset(`assets/catalog/page-${page}.jpg`)} alt={choose(lang,drawing?'Factory series outline drawing':'Factory series product photograph',drawing?'工厂样本系列外形图':'工厂样本系列产品照片')} loading="lazy" style={{width:`${1344/w*100}%`,left:`${-x/w*100}%`,top:`${-y/h*100}%`}}/></div>}
export function CompatibilityNotice({lang='en'}){return <aside className="compatibility"><strong>{choose(lang,'Compatibility notice','兼容性说明')}</strong><p>BITZER® is a trademark of its respective owner.<br/>BITZER model references are used solely for compatibility and product identification purposes.<br/>COOLMEIKE compressors are independently manufactured and are not original BITZER products.<br/>COOLMEIKE is not affiliated with, authorized by, sponsored by, or endorsed by BITZER.</p>{lang==='zh'&&<p>BITZER® 商标归其所有者所有，型号仅用于兼容参考及产品识别。COOLMEIKE 产品独立制造，非 BITZER 原厂产品，与 BITZER 无关联、授权、赞助或背书关系。</p>}</aside>}
export function ProductCard({product:p,lang}){return <article className="catalog-card"><a href={detailUrl(p)} aria-label={productTitle(p,lang)}><SourceFigure product={p} lang={lang}/></a><div className="catalog-card-body"><span className="eyebrow">COOLMEIKE · {p.cylinders} {choose(lang,'CYLINDERS','缸')}</span><h3><a href={detailUrl(p)}>{p.model}</a></h3><p>{nominalPowerText(p)}<br/>{p.displacementM3H} m³/h</p><small>{choose(lang,'Factory series photograph','工厂系列实拍')}</small><div className="catalog-actions"><a href={detailUrl(p)}>{choose(lang,'View Details','查看详情')} ↗</a><a href={asset(`?model=${encodeURIComponent(p.model)}#contact`)}>{choose(lang,'Request a Quote','询价')} →</a></div></div></article>}
export function CompareModels({lang}){return <div className="compare-block"><h3>{choose(lang,'Compare the essentials.','快速比较，精准选型。')}</h3><p>{choose(lang,'Compare factory sample specifications. Scroll horizontally on smaller screens.','对比工厂样本参数；小屏可左右滑动查看。')}</p><div className="table-scroll" tabIndex="0" role="region" aria-label={choose(lang,'Model comparison','型号对比')}><table><thead><tr>{choose(lang,['Model','HP','kW','Cylinders','Displacement (m³/h)','Net Weight (kg)'],['型号','HP','kW','气缸数','排气量 (m³/h)','净重 (kg)']).map(t=><th key={t} scope="col">{t}</th>)}</tr></thead><tbody>{popularProducts.map(p=><tr key={p.model}><th scope="row"><a href={detailUrl(p)}>{p.model} ↗</a></th><td>{p.nominalPower.hp}</td><td>{p.nominalPower.kw.toFixed(1)}</td><td>{p.cylinders}</td><td>{p.displacementM3H}</td><td>{p.netWeightKg}</td></tr>)}</tbody></table></div></div>}
export function FeaturedProducts({lang}){return <div className="featured"><p className="eyebrow">COOLMEIKE / SELECTED MODELS</p><h2>{choose(lang,'Find your compatible compressor.','找到适合你的兼容型压缩机。')}</h2><p className="catalog-lead">{choose(lang,'Six selected models. Independently manufactured. Explore the specifications, then discuss your application with our factory.','精选六款型号，独立制造。查看产品参数，与工厂沟通你的设备及应用需求。')}</p><div className="catalog-grid">{popularProducts.map(p=><ProductCard key={p.model} product={p} lang={lang}/>)}</div><CompareModels lang={lang}/><CompatibilityNotice lang={lang}/></div>}
export function SpecificationTable({product,lang}){return <div className="spec-grid">{specificationGroups(product,lang).map(g=><section key={g.title}><h3>{g.title}</h3><table><tbody>{g.rows.map(([k,v])=><tr key={k}><th scope="row">{k}</th><td>{v}</td></tr>)}</tbody></table></section>)}</div>}
export function InquirySummary({lang}){
 const [model,setModel]=useState(()=>{if(typeof window==='undefined')return '';const q=new URLSearchParams(window.location.search).get('model');return popularProducts.some(p=>p.model===q)?q:''}),[quantity,setQuantity]=useState(''),[customModel,setCustomModel]=useState(''),[copied,setCopied]=useState(false);
 const selectedModel=model==='other'?(customModel.trim()||'Other models - please advise'):model;
 const summary=`COOLMEIKE inquiry\nModel: ${selectedModel||'Please advise'}\nQuantity: ${quantity||'To be confirmed'}\nPlease provide a quotation and confirm application compatibility.`;
 const whatsapp=`https://wa.me/8619557964334?text=${encodeURIComponent(summary)}`;
 const email=`mailto:1748704761@qq.com?subject=${encodeURIComponent('COOLMEIKE quotation request'+(selectedModel?' - '+selectedModel:''))}&body=${encodeURIComponent(summary)}`;
 return <div className="inquiry-summary"><h3>{choose(lang,'Request a quote','获取报价')}</h3>
 <label>{choose(lang,'Model','型号')}<select value={model} onChange={e=>{setModel(e.target.value);setCopied(false)}}><option value="">{choose(lang,'Help me select','请协助选型')}</option>{popularProducts.map(p=><option key={p.model}>{p.model}</option>)}<option value="other">{choose(lang,'Other models','更多型号咨询')}</option></select></label>
 <button className="other-model-link" aria-expanded={model==='other'} aria-controls="other-model-fields" onClick={()=>{setModel('other');setCopied(false)}}>{choose(lang,'Looking for another model? Ask us →','没有找到所需型号？更多型号咨询 →')}</button>
 {model==='other'&&<div id="other-model-fields"><label>{choose(lang,'Model or requirements (optional)','型号或需求（选填）')}<input type="text" maxLength={300} value={customModel} onChange={e=>{setCustomModel(e.target.value);setCopied(false)}} placeholder={choose(lang,'Enter a model or describe your application','填写型号，或描述使用场景')}/></label><small>{choose(lang,'Not sure of the model? Leave this blank and send us a nameplate photo in WhatsApp or email.','不确定型号也可以留空，在 WhatsApp 或邮件中发送铭牌照片。')}</small></div>}
 <label>{choose(lang,'Quantity (optional)','数量（选填）')}<input type="number" min="1" step="1" value={quantity} onChange={e=>{setQuantity(e.target.value);setCopied(false)}}/></label>
 <div className="inquiry-channels"><a className="contact-pill" href={whatsapp} target="_blank" rel="noopener noreferrer">{choose(lang,'Chat on WhatsApp','WhatsApp 咨询')} ↗</a><a className="hero-quote" href={email}>{choose(lang,'Email your inquiry','邮件询价')} ↗</a></div>
 <button className="copy-button inquiry-copy" onClick={async()=>{try{await navigator.clipboard.writeText(summary);setCopied(true)}catch{window.prompt(choose(lang,'Copy inquiry','复制询价内容'),summary)}}}>{copied?choose(lang,'Copied','已复制'):choose(lang,'Copy inquiry details','复制询价内容')}</button>
 <small aria-live="polite">{choose(lang,'Your model and quantity will be included. Send the message in WhatsApp or your email app to complete your inquiry.','将自动带入型号与数量，请在 WhatsApp 或邮件应用中发送，完成询价。')}</small>
 <div className="nameplate-contact"><h4>{choose(lang,'Need a replacement compressor?','需要寻找替换压缩机？')}</h4><p>{choose(lang,'Add a clear nameplate photo in your WhatsApp chat or email. Include the model, voltage and refrigerant if known. Our team will help check compatibility.','请在 WhatsApp 聊天或邮件中添加清晰的铭牌照片。若已知，请提供型号、电源和制冷剂，由我们协助确认适配。')}</p></div></div>;
}
export function ProductDetail({product:p,staticLang}){const [lang,setLang]=useState(staticLang||initialLanguage);const l=(en,zh)=>choose(lang,en,zh);useEffect(()=>{const seo=productSeo(p,lang);document.title=seo.title;document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.querySelector('meta[name="description"]')?.setAttribute('content',seo.description);try{localStorage.setItem('minyou-language',lang)}catch{}},[lang,p]);const quote=asset(`?model=${encodeURIComponent(p.model)}#contact`);return <><header className="header"><a className="brand" href={asset('')}><BrandMark/></a><div className="header-actions"><a href={asset('#products')}>{l('All products','全部产品')}</a><button className="language" onClick={()=>setLang(lang==='en'?'zh':'en')}>{lang==='en'?'中文':'EN'}</button></div></header><main className="detail-page"><a className="breadcrumb" href={asset('#products')}>← {l('Products','产品中心')} / {p.model}</a><section className="detail-hero"><div><SourceFigure product={p} lang={lang}/><p className="image-caption">{l('Factory series photograph. Model configuration may vary.','工厂样本系列照片；具体型号配置可能不同。')}</p></div><div><p className="eyebrow">COOLMEIKE / {l('INDEPENDENTLY MANUFACTURED','独立制造')}</p><h1>{productTitle(p,lang)}</h1><p>{productDescription(p,lang)}</p><a className="contact-pill" href={quote}>{l('Request a Quote','获取报价')} ↗</a><a className="drawing-link" href="#drawing">{l('View outline drawing','查看外形图')} ↓</a></div></section><div className="metric-grid">{[[l('Nominal Power','名义功率'),nominalPowerText(p)],[l('Cylinders','气缸数'),p.cylinders],[l('Displacement','排气量'),`${p.displacementM3H} m³/h`],[l('Net Weight','净重'),`${p.netWeightKg} kg`]].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><section className="technical"><p className="eyebrow">01 / SPECIFICATIONS</p><h2>{l('Details that matter.','选型所需，一目了然。')}</h2><SpecificationTable product={p} lang={lang}/></section><section id="drawing" className="drawing-section"><p className="eyebrow">02 / OUTLINE</p><h2>{l('Factory series outline','工厂系列外形图')}</h2><SourceFigure product={p} drawing lang={lang}/><p>{l('Series drawing reproduced from the factory catalogue. Confirm the final configuration and mounting dimensions with us before installation.','外形图取自工厂样本，为系列示意。安装前请确认具体配置及安装尺寸。')}</p><a className="drawing-link" href={asset(p.technicalDrawing)} target="_blank" rel="noreferrer">{l('Open original catalogue page ↗','打开原始样本页 ↗')}</a><p className="dimension-line">A {p.dimensions.lengthMm} · B {p.dimensions.widthMm} · C {p.dimensions.heightMm} · D {p.dimensions.footingLengthMm} · E {p.dimensions.footingWidthMm} mm</p></section><CompatibilityNotice lang={lang}/><section className="detail-cta"><h2>{l('Let’s discuss your application.','把你的需求交给我们。')}</h2><a className="contact-pill" href={quote}>{l('Request a Quote','联系询价')} ↗</a></section></main><footer><strong>COOLMEIKE / 库美克</strong><p>Yuhuan Minzhu Refrigeration Industrial Co., Ltd.</p><p>玉环民主制冷实业有限公司</p></footer></>}
